language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
run: sdkmanager --install "ndk-bundle"
run: sdkmanager --licenses
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
  - chmod +x gradlew
script:
  - "./gradlew resguardDebug"
  - "./gradlew resguardBeta"
deploy:
  provider: releases
  api_key:
    secure: $github_token
  file_glob: true
  file:
    - app/build/outputs/apk/*/*/*/*aligned.apk
  skip_cleanup: true
  on:
    tags: true